import type { LandingConfig } from "@/shared/types";

export const LANDINGS: LandingConfig[] = [
  {
    id: "nexusai",
    name: "NexusAI",
    tagline: "El futuro de la productividad",
    description:
      "Plataforma SaaS de inteligencia artificial para automatización empresarial",
    industry: "SaaS / IA",
    theme: "Purple Dark",
    path: "/nexusai",
    image: "/NexusAI.avif",
  },
  {
    id: "vitality",
    name: "Vitality",
    tagline: "Transforma tu bienestar",
    description: "App de salud y fitness con coaching personalizado",
    industry: "Health / Fitness",
    theme: "Emerald Light",
    path: "/vitality",
    image: "/Vitality.avif",
  },
  {
    id: "helixbank",
    name: "Helix Bank",
    tagline: "Banca digital sin límites",
    description: "Fintech con cuentas digitales y crypto integrado",
    industry: "Fintech",
    theme: "Dark Cyan",
    path: "/helixbank",
    image: "/HelixBank.avif",
  },
  {
    id: "sentinel",
    name: "Sentinel Shield",
    tagline: "Protección inteligente",
    description: "Ciberseguridad empresarial con IA predictiva",
    industry: "Cybersecurity",
    theme: "Navy Cyan",
    path: "/sentinel",
    image: "/SentinelShield.avif",
  },
  {
    id: "lumina",
    name: "Lumina Learn",
    tagline: "Aprende sin límites",
    description: "Plataforma EdTech con cursos adaptativos",
    industry: "EdTech",
    theme: "Amber Indigo",
    path: "/lumina",
    image: "/LuminaLearn.avif",
  },
  {
    id: "compound",
    name: "Compound Growth",
    tagline: "Escala tu marketing",
    description: "Agencia B2B de marketing y growth hacking",
    industry: "B2B Marketing",
    theme: "Navy Gold",
    path: "/compound",
    image: "/CompoundGrowth.avif",
  },
  {
    id: "devcanvas",
    name: "DevCanvas",
    tagline: "Tu portafolio profesional",
    description: "Plataforma para crear portfolios de desarrolladores",
    industry: "Herramientas Dev",
    theme: "Violet Terminal",
    path: "/devcanvas",
    image: "/DevCanvas.avif",
  },
  {
    id: "nomadatlas",
    name: "Nomad Atlas",
    tagline: "Trabaja desde cualquier lugar",
    description: "Comunidad y recursos para nómadas digitales",
    industry: "Digital Nomad",
    theme: "Teal Orange",
    path: "/nomadatlas",
    image: "/NomadAtlas.avif",
  },
  {
    id: "keystone",
    name: "Keystone AI",
    tagline: "Inversiones inteligentes",
    description: "IA para análisis y valoración inmobiliaria",
    industry: "Real Estate AI",
    theme: "Forest Gold",
    path: "/keystone",
    image: "/KeystoneAI.avif",
  },
  {
    id: "ateliernoir",
    name: "Atelier Noir",
    tagline: "Elegancia atemporal",
    description: "E-commerce de moda de lujo artesanal",
    industry: "Luxury E-commerce",
    theme: "Charcoal Ivory",
    path: "/ateliernoir",
    image: "/AtelierNoir.avif",
  },
  // New 15 landings
  {
    id: "deployzero",
    name: "DeployZero",
    tagline: "Deploys sin configuración",
    description: "Plataforma de deploy serverless con zero configuration",
    industry: "Herramientas Dev",
    theme: "Cyan Dark",
    path: "/deployzero",
    image: "/DeployZero.avif",
  },
  {
    id: "uxpulse",
    name: "UXPulse",
    tagline: "Entiende a tus usuarios",
    description: "Analytics de UX con heatmaps y session replay",
    industry: "Analytics de UX",
    theme: "Rose Pink",
    path: "/uxpulse",
    image: "/UXPulse.avif",
  },
  {
    id: "apishield",
    name: "APIShield",
    tagline: "Protege tu API",
    description: "Seguridad de API con rate limiting y detección de amenazas",
    industry: "Seguridad de API",
    theme: "Emerald Dark",
    path: "/apishield",
    image: "/APIShield.avif",
  },
  {
    id: "microsaas",
    name: "MicroSaaS Builder",
    tagline: "Lanza más rápido, en solitario",
    description: "Boilerplate para indie makers con Stripe y auth incluido",
    industry: "Herramientas Dev",
    theme: "Orange Amber",
    path: "/microsaas",
    image: "/MicroSaasBuilder.avif",
  },
  {
    id: "designtokens",
    name: "DesignTokens Pro",
    tagline: "Design system sincronizado",
    description: "Sincroniza design tokens de Figma a código automáticamente",
    industry: "Herramientas Diseño",
    theme: "Pink Fuchsia",
    path: "/designtokens",
    image: "/DesignTokensPro.avif",
  },
  {
    id: "featureflag",
    name: "FeatureFlag Studio",
    tagline: "Despliega con confianza",
    description: "Feature flags con targeting y A/B testing integrado",
    industry: "Herramientas Dev",
    theme: "Teal Dark",
    path: "/featureflag",
    image: "/FeatureFlagStudio.avif",
  },
  {
    id: "performancelab",
    name: "PerformanceLab",
    tagline: "Web Vitals dominados",
    description: "RUM y Web Vitals monitoring para frontend teams",
    industry: "Performance",
    theme: "Purple Violet",
    path: "/performancelab",
    image: "/PerformanceLab.avif",
  },
  {
    id: "a11yscan",
    name: "A11yScan",
    tagline: "Accesibilidad primero",
    description: "Scanner de accesibilidad WCAG con CI integration",
    industry: "Accesibilidad",
    theme: "Blue Sky",
    path: "/a11yscan",
    image: "/A11yScan.avif",
  },
  {
    id: "frontendmonitor",
    name: "FrontendMonitor",
    tagline: "Detecta errores antes que tus usuarios",
    description: "Error tracking y session replay para aplicaciones frontend",
    industry: "Monitoreo",
    theme: "Red Alert",
    path: "/frontendmonitor",
    image: "/FrontendMonitor.avif",
  },
  {
    id: "seostack",
    name: "SEOStack",
    tagline: "SEO para desarrolladores",
    description:
      "Herramientas SEO diseñadas para developers y equipos técnicos",
    industry: "Herramientas SEO",
    theme: "Green Dark",
    path: "/seostack",
    image: "/SeoStack.avif",
  },
  {
    id: "saasonboarding",
    name: "SaaSOnboarding",
    tagline: "Activa más usuarios",
    description: "Plataforma de onboarding product-led para SaaS",
    industry: "Product Growth",
    theme: "Indigo Dark",
    path: "/saasonboarding",
    image: "/SaaSOnboarding.avif",
  },
  {
    id: "authless",
    name: "Authless",
    tagline: "Sin contraseñas. Solo auth.",
    description: "Autenticación passwordless con magic links y passkeys",
    industry: "Auth",
    theme: "Slate Minimal",
    path: "/authless",
    image: "/Authless.avif",
  },
  {
    id: "cloudcost",
    name: "CloudCost Guard",
    tagline: "Reduce el desperdicio cloud",
    description: "FinOps platform para optimización de costos cloud",
    industry: "Cloud FinOps",
    theme: "Blue Enterprise",
    path: "/cloudcost",
    image: "/CloudCostGuard.avif",
  },
  {
    id: "docsapi",
    name: "DocsAPI",
    tagline: "Documentación de API hermosa",
    description: "Documentación de API con playground y OpenAPI support",
    industry: "Docs para Devs",
    theme: "Violet Slate",
    path: "/docsapi",
    image: "/DocsAPI.avif",
  },
  {
    id: "indiemetrics",
    name: "IndieMetrics",
    tagline: "Tracking de MRR simple",
    description: "Analytics de SaaS para indie makers y solopreneurs",
    industry: "Analytics",
    theme: "Emerald Minimal",
    path: "/indiemetrics",
    image: "/IndieMetrics.avif",
  },
];
