import type { LandingConfig } from "@/shared/types";

export const LANDINGS: LandingConfig[] = [
  {
    id: "nexusai",
    name: "NexusAI",
    tagline: "El futuro de la productividad",
    description:
      "Plataforma SaaS de inteligencia artificial para automatización empresarial",
    industry: "SaaS / IA",
    theme: "Purple Dark",
    path: "/nexusai",
    image: "/NexusAI.png",
  },
  {
    id: "vitality",
    name: "Vitality",
    tagline: "Transforma tu bienestar",
    description: "App de salud y fitness con coaching personalizado",
    industry: "Health / Fitness",
    theme: "Emerald Light",
    path: "/vitality",
    image: "/Vitality.png",
  },
  {
    id: "helixbank",
    name: "Helix Bank",
    tagline: "Banca digital sin límites",
    description: "Fintech con cuentas digitales y crypto integrado",
    industry: "Fintech",
    theme: "Dark Cyan",
    path: "/helixbank",
    image: "/HelixBank.png",
  },
  {
    id: "sentinel",
    name: "Sentinel Shield",
    tagline: "Protección inteligente",
    description: "Ciberseguridad empresarial con IA predictiva",
    industry: "Cybersecurity",
    theme: "Navy Cyan",
    path: "/sentinel",
    image: "/SentinelShield.png",
  },
  {
    id: "lumina",
    name: "Lumina Learn",
    tagline: "Aprende sin límites",
    description: "Plataforma EdTech con cursos adaptativos",
    industry: "EdTech",
    theme: "Amber Indigo",
    path: "/lumina",
    image: "/LuminaLearn.png",
  },
  {
    id: "compound",
    name: "Compound Growth",
    tagline: "Escala tu marketing",
    description: "Agencia B2B de marketing y growth hacking",
    industry: "B2B Marketing",
    theme: "Navy Gold",
    path: "/compound",
    image: "/CompoundGrowth.png",
  },
  {
    id: "devcanvas",
    name: "DevCanvas",
    tagline: "Tu portafolio profesional",
    description: "Plataforma para crear portfolios de desarrolladores",
    industry: "Developer Tools",
    theme: "Violet Terminal",
    path: "/devcanvas",
    image: "/DevCanvas.png",
  },
  {
    id: "nomadatlas",
    name: "Nomad Atlas",
    tagline: "Trabaja desde cualquier lugar",
    description: "Comunidad y recursos para nómadas digitales",
    industry: "Digital Nomad",
    theme: "Teal Orange",
    path: "/nomadatlas",
    image: "/NomadAtlas.png",
  },
  {
    id: "keystone",
    name: "Keystone AI",
    tagline: "Inversiones inteligentes",
    description: "IA para análisis y valoración inmobiliaria",
    industry: "Real Estate AI",
    theme: "Forest Gold",
    path: "/keystone",
    image: "/KeystoneAI.png",
  },
  {
    id: "ateliernoir",
    name: "Atelier Noir",
    tagline: "Elegancia atemporal",
    description: "E-commerce de moda de lujo artesanal",
    industry: "Luxury E-commerce",
    theme: "Charcoal Ivory",
    path: "/ateliernoir",
    image: "/AtelierNoir.png",
  },
];
